name: Secret

on: push

jobs:
  checkout-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Secrets
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
