name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
