name: Super-Linter

on: push

jobs:    
  lint:
  
    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
      uses: github/super-linter@v7.1.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
